name: attriax_flutter_workspace
description: Workspace configuration for the Attriax Flutter monorepo.
publish_to: none

environment:
  sdk: ^3.8.0

workspace:
  - attriax
  - attriax_sdk_client
  - attriax/example
  - attriax_android
  - attriax_ios
  - attriax_platform_interface
