name: attriax_platform_interface
description: A common platform interface for the Attriax plugin.
version: 1.0.0
homepage: https://attriax.com
repository: https://github.com/attriax/flutter-plugin
issue_tracker: https://github.com/attriax/flutter-plugin/issues
topics:
  - attribution
  - flutter-plugin

environment:
  sdk: ^3.8.0
  flutter: ">=3.29.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
