name: attriax_api_client
version: 0.5.0
description: Generated Attriax SDK API client.
homepage: https://attriax.com
resolution: workspace
repository: https://github.com/attriax/sdk-flutter
issue_tracker: https://github.com/attriax/sdk-flutter/issues
topics:
  - attribution
  - api-client
  - sdk-flutter


environment:
  sdk: ^3.8.0

dependencies:
  dio: '^5.7.0'
  json_annotation: '^4.9.0'

dev_dependencies:
  build_runner: any
  json_serializable: '^6.9.3'
  test: '^1.16.0'
