// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC9xEOmRORdHn5NMicyii4jSRbhOGOgIk',
    appId: '1:506992298122:web:a5428c767f25e468e3c573',
    messagingSenderId: '506992298122',
    projectId: 'attriax-example',
    authDomain: 'attriax-example.firebaseapp.com',
    storageBucket: 'attriax-example.firebasestorage.app',
    measurementId: 'G-YHGSRML9Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-Cq2C6XiLQuipNo4K39WbTfIWI0u7sMA',
    appId: '1:506992298122:android:d240247c31ef56a0e3c573',
    messagingSenderId: '506992298122',
    projectId: 'attriax-example',
    storageBucket: 'attriax-example.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBINkhWMoFKx0uaqsnVIW-HGsXKYTBeHfE',
    appId: '1:506992298122:ios:be94be75b4933c09e3c573',
    messagingSenderId: '506992298122',
    projectId: 'attriax-example',
    storageBucket: 'attriax-example.firebasestorage.app',
    iosBundleId: 'com.attriax.attriaxExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBINkhWMoFKx0uaqsnVIW-HGsXKYTBeHfE',
    appId: '1:506992298122:ios:be94be75b4933c09e3c573',
    messagingSenderId: '506992298122',
    projectId: 'attriax-example',
    storageBucket: 'attriax-example.firebasestorage.app',
    iosBundleId: 'com.attriax.attriaxExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC9xEOmRORdHn5NMicyii4jSRbhOGOgIk',
    appId: '1:506992298122:web:6d7779ddc84d421fe3c573',
    messagingSenderId: '506992298122',
    projectId: 'attriax-example',
    authDomain: 'attriax-example.firebaseapp.com',
    storageBucket: 'attriax-example.firebasestorage.app',
    measurementId: 'G-9ZM1S4BK5L',
  );
}
